name: Conda Environment

on:
  # To run manually
  workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          channels: conda-forge, defaults
          use-only-tar-bz2: true  # IMPORTANT: This needs to be set for caching to work properly!
          auto-update-conda: true
          auto-activate-base: true
          activate-environment: scipy
          python-version: 3.10
    
      - name: Install conda packages
        shell: pwsh
        run: conda install scipy

      - name: Hello World 
        run: |
          python -c "import scipy as sp; print('Scipy version: '+sp.__version__)"
