name: Conda Environment

on:
  # To run manually
  workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          channels: conda-forge, defaults
          activate-environment: scipy
          python-version: 3.10
      - name: Conda list
        shell: pwsh
        run: conda list
