name: Ambient Sound Processing

on:
  # To run manually
  workflow_dispatch:
  # schedule:
  #  - cron: '9 * * * *'
    
jobs:
  process:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9.18'

    - name: Install Python dependencies
      run: |
        python -m pip install -U pip
        python -m pip install -U setuptools wheel
        python -m pip install -r ambient_sound_analysis/requirements_noise.txt

 
    - name: Install ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get install ffmpeg

    - name: Create plots
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        python ambient_sound_analysis/noise_processing.py

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
          commit_message: Commit to Github
          file_pattern: 'ambient_sound_analysis/img/*.png'
