# Batch process many image pairs
name: summary_statistics
run-name: summary_statistics

on:
  workflow_dispatch:
  workflow_call:

jobs:
    summary_statistics:
        name: summary_statistics
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash -el {0}

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Install Conda environment with Micromamba
              uses: mamba-org/setup-micromamba@v1
              with:
                cache-environment: true
                environment-file: glacier_image_correlation/environment.yml
                environment-name: image-correlation

            - name: Download Artifacts
              uses: actions/download-artifact@v4
              with:
                  path: glacier_image_correlation/
                  merge-multiple: true
                
            - name: Compute summary statistics
              run: |
                python glacier_image_correlation/summary_statistics.py

            - name: Upload summary statistics
              uses: actions/upload-artifact@v4
              with:
                name: summary_statistics
                path: |
                    glacier_image_correlation/velocity_summary_statistics.png
